# GitLab CI/CD configuration
stages:
  - test
  - build
  - deploy

test:
    stage: test
    image: python:3.10
    script:
        - pip install --upgrade pip
        - pip install -e .
        - MPLBACKEND=Agg python tests/test_centrif_compressor.py

build:
    stage: build
    image: python:3.10
    script:
        - pip install --upgrade pip
        - pip install -e .
        - pip install sphinx sphinx_rtd_theme
        - cd docs
        - make html
        - cd ../
    artifacts:
        untracked: true

pages:
    stage: deploy
    script:
        - mkdir .public
        - cp -r docs/build/html/* .public
        - mv .public public
    artifacts:
        paths:
            - public
    only:
        - main
